import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Draggable from 'react-draggable'
import React, { useEffect, useState } from 'react';

const song1 = "Her Song Was Like a Prophecy";

const songList = ["Her Song Was Like a Prophecy", "An Open Letter to My Best Friend", "Snow Day", "Eighteen", "You Held On Tight To Me", 
"In Another World", "Circus", "Blood Runs Thick", "Seventh Grade"];

// ==============================================================

const getRandomASCII = () => {
    return songList[Math.floor(Math.random() * songList.length)];
};

// ==========================================================================================================================================
// ==========================================================================================================================================
// ==========================================================================================================================================

function NavBar() {

    // ==============================================

    // ==============================================

    const [ASCIIplace, setASCIIplace] = useState(song1);

    useEffect(() => setASCIIplace(getRandomASCII()), [])

    const changeRandomASCII = () => {
        // shuffle array and pick random
        const randomASCII = getRandomASCII();
        setASCIIplace(randomASCII);
    };

    return (
        <div className={styles.container}>

            <Head>
                <title>ula bitinaitis</title>
                <meta name="description" content="generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Draggable>
                <img src="/websitebanner.gif" draggable="false" style={{
                    width: 640 * .75, height: 390 * .75, alt: "ula bitinaitis", objectFit: "cover",
                    onmousedown: "return false", userdrag: "none", position: "relative", top: "50px", left: "70px"
                }} />
            </Draggable>


            <Draggable>
                <div className="littlebutton" style={{ position: "relative", top: "-250px", left: "620px" }}>
                    <div className="candywrappink">
                        <a href="/about">about me!</a> ❤
                    </div>
                </div>
            </Draggable>

            <Draggable>
                <div className="littlebutton" style={{ position: "relative", top: "-450px", left: "1250px" }}>fun things you can do:</div>
            </Draggable>


            <Draggable>
                <div className="littlebutton" style={{ position: "relative", top: "-450px", left: "1250px" }}>
                    <div className="candywrapgreen">
                        <Link href={"https://docs.google.com/document/d/1qNBZSG3nfc_zMkDL9os0c4fB2IgZKLLWKeex-YcnLKs/edit?usp=sharing"}>
                            <a target="_blank">
                                view my bread recipe</a>
                        </Link> ❤</div></div>
            </Draggable>



            <Draggable>
                <div className="littlebutton" style={{ position: "relative", top: "-450px", left: "1200px" }}>
                    <div className="candywrappurple">
                        <a href="javascript:void(0)" onClick={changeRandomASCII}>
                            change the ASCII</a > ❤
                    </div>
                </div>
            </Draggable>



            {/* <Draggable>
                <div className="littlebutton" style={{ position: "relative", top: "-450px", left: "1250px" }}>
                    <div className="candywrappink">
                        <a href="javascript:void(0)" onClick={addBunny}>
                            create a new bunny ❤</a>
                    </div>
                </div>
            </Draggable> */}



            <Draggable>
                <div className="littlebutton" style={{ position: "relative", top: "-200px", left: "1300px", marginTop: "-250px" }}>
                    <div className="candywraporange">
                        <a href="/friends">see my friends!</a>❤</div></div>
            </Draggable>

            <Draggable>
                <pre style={{
                    fontFamily: "MS PGothic", position: "absolute", left: "1100px", top: "400px",
                    display: "inline-block", backgroundColor: "transparent",
                }}>
                    {ASCIIplace}
                </pre>
            </Draggable>

            <Draggable>
                <img src="/partyhat.gif" draggable="false" style={{ objectFit: "cover", width: "90px",
                    onmousedown: "return false", userdrag: "none",
                    position: "absolute", top: "30px", left: "1100px", zIndex: "999999"
                }} />
            </Draggable>

            <Draggable>
                <img src="/bowtie.gif" draggable="false" style={{ objectFit: "cover", width: "130px",
                    onmousedown: "return false", userdrag: "none",
                    position: "absolute", top: "30px", left: "1100px", zIndex: "999999"
                }} />
            </Draggable>

            <Draggable>
                <img src="/flower.gif" draggable="false" style={{ objectFit: "cover", width: "80px",
                    onmousedown: "return false", userdrag: "none",
                    position: "absolute", top: "30px", left: "1100px", zIndex: "999999"
                }} />
            </Draggable>

            <Draggable>
                <img src="/glasses.gif" draggable="false" style={{ objectFit: "cover", width: "160px",
                    onmousedown: "return false", userdrag: "none",
                    position: "absolute", top: "30px", left: "1100px", zIndex: "999999"
                }} />
            </Draggable>

            <Draggable>
                <img src="/magnifyingglass.gif" draggable="false" style={{ objectFit: "cover", width: "130px",
                    onmousedown: "return false", userdrag: "none",
                    position: "absolute", top: "30px", left: "1100px", zIndex: "999999"
                }} />
            </Draggable>
        </div>

    )

}

export default NavBar