import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class ="thebigimage">
        <div class="input-wrapper">
            <span class="welcome"></span>
        </div>
      </div>


      <footer className={styles.footer}>
        <a
          href="https://github.com/ubitinaitis"
          target="_blank"
          rel="noopener noreferrer"
        >
          by ula bitinaitis ♡ Next.js
        </a>
      </footer>
    </div>
  )
}
